=== wangyoushun/mybatisDemo/src/main/resources/mydb-config.dtd
<?xml version="1.0" encoding="UTF-8" ?>

<!--mydb 1.0 -->
<!ELEMENT configuration (properties?, settings?, environments?, mappers?)>

<!ELEMENT properties (property*)>
<!ATTLIST properties
resource CDATA #IMPLIED
url CDATA #IMPLIED
>

<!ELEMENT property EMPTY>
<!ATTLIST property
name CDATA #REQUIRED
value CDATA #REQUIRED
>

<!ELEMENT settings (setting+)>

<!ELEMENT setting EMPTY>
<!ATTLIST setting
name CDATA #REQUIRED
value CDATA #REQUIRED
>


<!ELEMENT environments (environment+)>

<!ELEMENT environment (transactionManager,dataSource)>
<!ATTLIST environment
id CDATA #REQUIRED
>

<!ELEMENT transactionManager (property*)>
<!ATTLIST transactionManager
autoCmit CDATA #REQUIRED
>

<!ELEMENT dataSource (property*)>

<!ELEMENT mappers (mapper*)>

<!ELEMENT mapper EMPTY>
<!ATTLIST mapper
resource CDATA #IMPLIED
>

=== wangyoushun/mybatisDemo/src/main/resources/mydb-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE configuration SYSTEM "mydb-config.dtd">
<configuration>
	<properties resource="datasource.properties">
		<property name="test" value="test123" />
	</properties>
	<settings>
		<setting name="mapUnderscoreToCamelCase" value="true" />
		<setting name="logTime" value="true" />
	</settings>

	<environments>
		<environment id="development">
			<transactionManager autoCmit="false"></transactionManager>
			<dataSource>
				<property name="driver" value="${driver}" />
				<property name="url" value="${url}" />
				<property name="username" value="${username}" />
				<property name="password" value="${password}" />
			</dataSource>
		</environment>
	</environments>

	<mappers>
		<mapper resource="sql/User.sql" />
		<mapper resource="com/six/mydb/mapper/MapperProxy.sql" />
	</mappers>
</configuration>
